public class ProdDemoController {
	
	//Sesresult method
    public PageReference seeresult() {
        return null;
    }
    
   public static Integer myValue = 0; //Class Member variable
   public static String myString = ''; //Class Member variable
   
   //find dealer
   public static Integer FindDealer () {
   	Integer i=0;
   	return i;
      
   }

	//variables 
    public String l { get; set; }

    public String tobacconicotineuse { get; set; }

    public String yearOptions { get; set; }

    public String yearofbirth { get; set; }

    public String monthOptions { get; set; }

    public String monthofbirth { get; set; }

    public String openPresentationOptions { get; set; }

    

    public String DateofBirth{get;set;}
    public String model{get;set;}
    public Integer type{get;set;}
    public String Budget{get;set;}
    public String Loan{get;set;}
    public String State{get;set;}
    public String City{get;set;}
    public Integer FormatType{get;set;}
    public ProdDemoController(){
        
    }
   
        
    
}