)]}'
[

  {

    "approvals": {

      "Code-Review": "+2"

    },

    "_account_id": 21,

    "name": "ashish.b.srivastava",

    "email": "ashish.b.srivastava@accenture.com",

    "username": "ashish.b.srivastava"

  },

  {

    "approvals": {

      "Code-Review": "+2"

    },

    "_account_id": 22,

    "name": "p.rameshwar.wayal",

    "email": "p.rameshwar.wayal@accenture.com",

    "username": "p.rameshwar.wayal"

  }

]