)]}'
{
  "Administrators": {
    "url": "#/admin/groups/uuid-9f7cbaa6d17bdee512696feb6a67c2e5dc0c3cca",
    "options": {},
    "description": "Gerrit Site Administrators",
    "group_id": 1,
    "owner": "Administrators",
    "owner_id": "9f7cbaa6d17bdee512696feb6a67c2e5dc0c3cca",
    "id": "9f7cbaa6d17bdee512696feb6a67c2e5dc0c3cca"
  },
  "Non-Interactive Users": {
    "url": "#/admin/groups/uuid-ec8212e406014b17d52120bbdf185fd7a7731ced",
    "options": {},
    "description": "Users who perform batch actions on Gerrit",
    "group_id": 2,
    "owner": "Administrators",
    "owner_id": "9f7cbaa6d17bdee512696feb6a67c2e5dc0c3cca",
    "id": "ec8212e406014b17d52120bbdf185fd7a7731ced"
  },
  "Reviewer": {
    "url": "#/admin/groups/uuid-ee4c789915b9bb6b0b3089fe9134365ddf863558",
    "options": {},
    "group_id": 3,
    "owner": "Reviewer",
    "owner_id": "ee4c789915b9bb6b0b3089fe9134365ddf863558",
    "id": "ee4c789915b9bb6b0b3089fe9134365ddf863558"
  }
}